- include: getEnv.yaml
- name: Check if we have loaded the module
  lineinfile:
    dest="{{ HttpConfPath }}"
    line="LoadModule security2_module {{ ModSecModulePath }}"
    regexp="^\s*?LoadModule\ssecurity2_module\s.*?.so$"
    state=present
    insertafter=EOF
- name: Check if we have added our include
  lineinfile:
    dest="{{ HttpConfPath }}"
    line="IncludeOptional modsecurity.d/*.conf"
    regexp="^IncludeOptional modsecurity\.d\/\*\.conf$"
    state=present
    insertafter=EOF
- name: Create modsecurity.d directory
  file: path="{{ HttpServerRoot }}/modsecurity.d" state=directory
- name: Clone owasp CRS
  git: repo=git://github.com/SpiderLabs/owasp-modsecurity-crs
    dest={{ HttpServerRoot }}/modsecurity.d/owasp-crs/
    version={{crs_version}}
    update=no
- name: Check if example already renamed (v2)
  stat: path="{{ HttpServerRoot }}/modsecurity.d/owasp-crs/modsecurity_crs_10_setup.conf.example"
  register: exampleStat
- name: Check if example already renamed (v3)
  stat: path="{{ HttpServerRoot }}/modsecurity.d/owasp-crs/crs-setup.conf.example"
  register: exampleStatv3
- name: Rename setup.example to .conf (v2)
  command: "mv {{ HttpServerRoot }}/modsecurity.d/owasp-crs/modsecurity_crs_10_setup.conf.example {{ HttpServerRoot }}/modsecurity.d/owasp-crs/modsecurity_crs_10_setup.conf"
  when: exampleStat.stat.exists and crs_version == "v2.2/master"
- name: Rename setup.example to .conf (v3)
  command: "mv {{ HttpServerRoot }}/modsecurity.d/owasp-crs/crs-setup.conf.example {{ HttpServerRoot }}/modsecurity.d/owasp-crs/modsecurity_crs_10_setup.conf"
  when: exampleStatv3.stat.exists and crs_version == "v3.0/master"
- name: Check if includeOWASP.conf already written
  stat: path="{{ HttpServerRoot }}/modsecurity.d/includeOWASP.conf"
  register: owaspStat
- name: Add a script to load our CRS Rules (v3)
  copy: content="Include modsecurity.d/owasp-crs/*.conf\nInclude modsecurity.d/owasp-crs/rules/*.conf" dest="{{ HttpServerRoot }}/modsecurity.d/includeOWASP.conf"
  when: not owaspStat.stat.exists and crs_version == "v3.0/master"
- name: Add a script to load our CRS Rules (v2)
  copy: content="Include modsecurity.d/owasp-crs/*.conf\nInclude modsecurity.d/owasp-crs/base_rules/*.conf" dest="{{ HttpServerRoot }}/modsecurity.d/includeOWASP.conf"
  when: not owaspStat.stat.exists and crs_version == "v2.2/master"
