---
# tasks file for drupal7_resources_retrieve
- name: dump directory exists.
  file:
    path: "{{ retrieve_path }}/db"
    state: directory
    owner: "{{ distant_source_user }}"
    group: "{{ distant_source_user }}"

- name: Dump database
  community.mysql.mysql_db:
    state: dump
    name: "{{ drupal_db_name }}"
    login_user: "{{ drupal_db_user }}"
    login_password: "{{ drupal_db_passwd }}"
    target: "{{ retrieve_path }}/db/{{ drupal_db_name }}.gz"

- name: fetch db on local
  ansible.builtin.fetch:
    src: "{{ retrieve_path }}/db/{{ drupal_db_name }}.gz"
    dest: "{{ retrieve_path }}/db/{{ drupal_db_name }}.gz"
    flat: yes


- name: dump directory exists.
  file:
    path: "{{ retrieve_path }}/files"
    state: directory
    owner: "{{ distant_source_user }}"
    group: "{{ distant_source_user }}"


- name: Compress Directory files
  become: yes
  archive:
    path: "{{ ovh_drupal_core_path }}/sites/00_algol_websites/files/c02"
    dest: "{{ retrieve_path }}/files/c02_files.gz"
    format: gz

- name: fetch files on local
  ansible.builtin.fetch:
    src: "{{ retrieve_path }}/files/c02_files.gz"
    dest: "{{ retrieve_path }}/files/c02_files.gz"
    flat: yes